version: 0.2

phases:
    install:
        commands:
            - cd front-ts && npm install
    pre_build:
        commands:
            - npm run ci:build
    build:
        commands:
            - npm start & npx wait-on http://localhost:3000
            - ./node_modules/.bin/cypress run
